---
apiVersion: v1
kind: Secret
metadata:
  name: questcode
  namespace: production
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9hZG1pbnVzZXI6YWRtaW5AYm9vdGNhbXAtZGV2b3BzLnpxYjEzLm1vbmdvZGIubmV0L215Rmlyc3REYXRhYmFzZT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  SECRET_OR_KEY: [COLOCAR_BASE64_AQUI]
---
apiVersion: v1
kind: Secret
metadata:
  name: questcode
  namespace: staging
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9hZG1pbnVzZXI6YWRtaW5AYm9vdGNhbXAtZGV2b3BzLnpxYjEzLm1vbmdvZGIubmV0L215Rmlyc3REYXRhYmFzZT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  SECRET_OR_KEY: [COLOCAR_BASE64_AQUI]